
service: api-serverless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*        
      Resource:
        - arn:aws:dynamodb:us-east-1:285112773994:table/StartWarPeopleTable

functions:
  startWar:
    handler: handler.handler
    events:      
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true

resources:
  Resources:
    StartWarPeopleTable:
      Type: 'AWS::DynamoDB::Table'
      Properties: 
        TableName: StartWarPeopleTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: nombre
            AttributeType: S
        KeySchema:
            - AttributeName: nombre
              KeyType: HASH  

